---

- name: Stat
  stat: path={{cloud_watch_monitoring_path}}/aws-scripts-mon
  register: scripts_dir

- name: Setup Amazon CloudWatch Monitoring Scr
  import_tasks: prereq.yml
  when: scripts_dir.stat.exists == False

- name: Setup Cron
  import_tasks: cron_setup.yml
  become: False
