---

- name: "Install apt packages"
  apt: name={{ item }} state=present
  with_items: ['unzip','libwww-perl',  'libdatetime-perl']
  when: ansible_os_family == "Debian"
  become: True
  become_method: sudo

- name: "Install yum packages"
  yum: name={{ item }} state=present
  with_items: ['unzip', 'perl-Switch', 'perl-DateTime', 'perl-Digest-SHA', 'perl-Sys-Syslog', 'perl-LWP-Protocol-https']
  when: ansible_os_family == "RedHat"
  become: True
  become_method: sudo

- name: "Install zypper packages"
  zypper: name={{ item }} state=present
  with_items: ['perl-Switch', 'perl-DateTime',  'perl(LWP::Protocol::https)']
  when: ansible_os_family == "Suse"
  become: True

- name: Download Amazon CloudWatch Monitoring Scripts
  get_url: url=http://aws-cloudwatch.s3.amazonaws.com/downloads/CloudWatchMonitoringScripts-1.2.1.zip dest=/tmp/CloudWatchMonitoringScripts-1.2.1.zip

- name: Unarchive zip
  unarchive: src=/tmp/CloudWatchMonitoringScripts-1.2.1.zip dest={{ cloud_watch_monitoring_path }} copy=no
  become: True

- name: Delete zip file
  file: path=/tmp/CloudWatchMonitoringScripts-1.2.1.zip state=absent
